### ISSUE TITLE
something wrong with JSON format in Copper

### ISSUE THREAD

**Issue by shantanoo-desai** [mkovatsc/Copper#11]
Hello Mr. Kovatsch, 
I am using Zolertia Z1 motes which implement resources like information of parent node, and routing information using GET request.
the format is <pre>{"parent": eui of parent, "pref": true, etx: aaa} for parent </pre>
for routing is<pre> {"dest": mac of destination, "next": next hop address}</pre>
there are some other resources too on the CoAP. 
Every time try getting a GET for Parent or route info Copper starts running into a like a infinite loop state while showing only a certain characters of requested JSON format. 

the code has been written using erbium and there seems to be no issue when implemented using a different implementation like SMCP. Could there be a potential glitch in Copper when parsing JSON?

would like you help on this matter. 
for my implementation  with a complete README --> (https://github.com/shantanoo-desai/coap-wsn)
(Note: I checked the implementation out by directly connecting a border router to my linux PC and though the resources are discovered and TEXT_PLAIN formats are returned there is only a problem with JSON formating.)

thank you for the plugin though, it is fun to play with Copper.

Regards 
Shan

**Comment by mkovatsc** [comment]
I checked by writing JSON to coap://californium.eclipse.org:5683/large-update and when I GET it with Copper, I have no issues in the current version. Could you provide a wireshark trace? Maybe also paste the exact payload here.

**Comment by shantanoo-desai** [comment]
hi Mr. Kovatsch, This is the 
PCAP of the Issue I was talking about
https://drive.google.com/file/d/0B1qhSdvn56atcU5BbHIxOEsxNnc/view?usp=sharing

(Captured using Wireshark Version 1.12.3 (v1.12.3-0-gbb3e9a0 from master-1.12))
this snapshot shows that the well-known core is discovered perfectly:
![mkovatsch-1](https://cloud.githubusercontent.com/assets/12070966/8508624/db28d21c-2277-11e5-9795-e807a5a6b285.png)

this is when I do the following 
<pre>GET /rplinfo/parents?index=0</pre>
![mkovatsch-2](https://cloud.githubusercontent.com/assets/12070966/8508628/06cd1130-2278-11e5-9da9-29e023ca7620.png)

Setup: 1 Zolertia Z1 mote as coap-server

**Comment by mkovatsc** [comment]
The pcap shows that the server keeps sending the first block despite increasing the block number. Hence, the problem lies in your resource implementation. In your parents_handler() C-code, I cannot see you using the offset to generate the right block...

**Comment by shantanoo-desai** [comment]
Hi Matthias, 
I figured it out. Thanks. Actually the `*offset` wasn't required at all. Hence I removed it an now I get the rendered JSON form of my data. thank you for pointing it out.
