### ISSUE TITLE
feature suggestion: cbor

### ISSUE THREAD

**Issue by chrysn** [mkovatsc/Copper#15]
with cbor being present in newer versions of senml, in the core-links-json draft and the yang-cbor-mapping, it is likely to be present in many upcoming debugging situations in which copper is used.

libraries for decoding cbor in javascript [already exist](http://cbor.io/impls.html).

cbor could be visualized in the "Rendered" tab just as json is.

**Comment by mkovatsc** [comment]
I know, there is even an open pull-request (Oic dev #13) from last year that I did not have the time to review yet (shame on me! :) ).

It would be helpful to split #13 up into multiple PRs, so I can merge individual features, since it is much easier to to decide and also review...

**Comment by stephanesan** [comment]
Yes, the pull request add multiple new functionalities. But because they are successive patches, the integration order of the patches is important to avoid merge conflicts. Is it feasible for you to cherry pick the patches one by one to ease the review?

**Comment by mkovatsc** [comment]
Partially merged @stephanesan 's PR in 1.0.1 -- thanks!
BTW: coap://californium.eclipse.org:5683/multi-format now also offers CBOR.
