### ISSUE TITLE
URIs with zone index unsupported

### ISSUE THREAD

**Issue by chrysn** [mkovatsc/Copper#18]
IPv6 link-local addresses can require a zone index that usually indicates the local link the address is valid on; an example would be `coap://[fe80::12:34ff:fe56:78ab%tap0]/`. With Firefox 45.2.0, entering such an address results in a "The address wasn't understood" error message, and the address bar gets trimmed to a single `:`.

The behavior can easily be tested on Linux with a local server if you have any `fe80:` address on a local interface by appending the interface's name to the address; other operating systems could use different zone identifiers.

**Comment by mkovatsc** [comment]
See #12
It is unsupported by Firefox.

**Comment by chrysn** [comment]
Sorry for not having looked up the closed bugs.

The underlying firefox issue is being discussed in [bugzilla's #700999](https://bugzilla.mozilla.org/show_bug.cgi?id=700999)
