### ISSUE TITLE
Mozilla broke protocol handler extensions

### ISSUE THREAD

**Issue by mkovatsc** [mkovatsc/Copper#20]
Mozilla made development and testing quite annoying and broke the support for protocol handler extensions in the Developer Version (FF50). Not sure if there will be a working Copper in the future...

**Comment by mkovatsc** [comment]
Quick fix:

1) Open `about:config`
2) Search `browser.tabs.remote.autostart.2`
3) Set to `false`

**Comment by jamesmunns** [comment]
Thanks!

**Comment by deltahotel** [comment]
Unfortunaltely this workaround doesn't work for me with FF 50.0.2, FF still complains about the unknown protocol.

**Comment by mkovatsc** [comment]
Can you provide a screenshot and system information?
Under Windows it works with FF 50.0.2.

**Comment by deltahotel** [comment]
Thanks for your prompt response! I did some more investigation and it turned out that `browser.tabs.remote.autostart` also needs to be set to `false` as well (default is `true` with a newly created Firefox profile). Having that set, Copper works fine again. I'm using the x86-64 Linux package.

**Comment by mkovatsc** [comment]
Since FF52 this autostart is disabled automatically when required by add-ons.

FF57, which is planned for September, might disable Copper for good, as they change to a new [WebExtensions](https://developer.mozilla.org/en-US/Add-ons/WebExtensions) model for add-ons... so far no time to look into it.
