### ISSUE TITLE
Slow blockwise upload, 100% CPU load, ultimately fails

### ISSUE THREAD

**Issue by rfjakob** [mkovatsc/Copper#21]
Trying to PUT a 100kB file with 256B blocks runs slow and ultimately fails with a timeout. Checking with Wireshark shows that Copper waits about 2 seconds after getting the ACK before sending the next block:
![pcap](https://cloud.githubusercontent.com/assets/286847/19358475/59181c64-9176-11e6-90ad-f4b061213b56.png)
The Firefox process spins at 100% CPU during the upload.

PS: Thanks for the plugin, great work!

**Comment by rfjakob** [comment]
Interestingly, the message log tells a different story. According to the log, there is no gap between ACK and PUT:
![message log](https://cloud.githubusercontent.com/assets/286847/19358718/38dd88a2-9177-11e6-866a-85a94ba31a2c.png)
However, this is incorrect as seen in the Wireshark log. The packet just seems to take 2 seconds to process inside Copper.

Uploading the file through coap-client from libcoap finishes in 29 seconds.

**Comment by mkovatsc** [comment]
As mentioned in the PR, it is the renderer loop for binary that is super slow and needs to be reworked with cached sub-results...
