### ISSUE TITLE
Blockwise transfer problem during Observe with more than one tab

### ISSUE THREAD

**Issue by darkopetrovic** [mkovatsc/Copper#25]
I open several tabs for different sensors and when I use the Observre function with each of them and switch between the tabs, when the plugin (the tab) loose focus it request the wrong resource during the blockwise transfer. When I switch back it works again properly. Here a picture of the messages log: 

![2016-12-13_111136](https://cloud.githubusercontent.com/assets/1554288/21136315/71379e44-c125-11e6-9a7a-bfccbd503f9d.png)

No such problem existed with the previous version.

**Comment by mkovatsc** [comment]
I did not change anything in the logic. The tabs should be fully isolated.

Sounds like there is now some kind of cross-talk? That sounds like a huge problem in Mozilla's multi-process architecture... they are currently converting the inner doings. I am not even sure what will happen to protocol handlers in the future.. :/

**Comment by darkopetrovic** [comment]
Indeed you're right there is a cross-talk between the tabs. When I ask the same resources for the sensors there isn't such problem. Ok this issue is not related to the plugin then :)

**Comment by mkovatsc** [comment]
Might have been a bug in e10s. Works at the moment.
