### ISSUE TITLE
observer repsonse

### ISSUE THREAD

**Issue by kanishkablack** [mkovatsc/Copper#26]
I have found a small issue if client tries to observe any resource, irrespective of response, the client starts to listen to the resource.

**Comment by mkovatsc** [comment]
Please elaborate :)
A screenshot of the message kog might help.

Also make sure it is not happening because of "display rejected" behavior or similar debug functionality.

**Comment by kanishkablack** [comment]
![2017-03-27 20_26_48-settings](https://cloud.githubusercontent.com/assets/949292/24362900/d213b128-132b-11e7-8bd9-bf375b7c4157.png)

When the response from server as 4.03, still the client starts to observe 

i am not sure, its UI glitch or a real bug

**Comment by mkovatsc** [comment]
The problem is that your server includes the Observe option in the response :)
