### ISSUE TITLE
Copper with firefox 52 on raspberry pi3

### ISSUE THREAD

**Issue by Shellkan** [mkovatsc/Copper#32]
Hi,
For a school project i need to use Copper with firefox on a  raspberry Pi 3B with ubuntu mate.
To use Copper, i downgraded firefox to firefox 52. Then i followed instructions to install copper but any Add ons appear on firefox.
I don"t  what is wrong, so i need help...

Sorry if my english isn't very correct, i'm a french guy =)

**Comment by mkovatsc** [comment]
Have you read https://github.com/mkovatsc/Copper#not-supported-by-firefox-56--webextensions-api?
The `about:config` steps are important ;)

**Comment by Shellkan** [comment]
yes i did.

What i`ve done :

1.Downgrade firerox to firefox 52.02(32 bit)
2.Download Copper directory
3.Create the copper@vs.inf.ethz.ch file like this (see image)
![Capture](https://user-images.githubusercontent.com/51420120/59044111-8235cf00-884b-11e9-9e4b-703c0ce4bec9.PNG)

4.My Copper directory is in my Download directory, so i have edited the file like this :
    `~\Téléchargements\Copper\`
5.Then I have allowed unsigned add-ons:
![Capture2](https://user-images.githubusercontent.com/51420120/59044536-4bac8400-884c-11e9-86a8-7b95dff610f6.PNG)
6.Finally i restart firefox but i have this message in extensions field 
`you don't have any add-ons of this type installed`

**Comment by mkovatsc** [comment]
Have you disabled auto-updates? It updates very persistently if you are online.. maybe double-check your current version.

I haven't worked on this in a while. Double-check if the trailing slash in the path makes a different. And at some point, an "autoreg" file was needed. Maybe you can retry with version 55.

**Comment by Shellkan** [comment]
yes, auto-update is disable,my firefox is still in version 52.
I already tried with differents path...
`~\Téléchargements\Copper\` and `~/Téléchargements/Copper/` and `~\Téléchargements\Copper`but the issue is the same :/
i wanted to install version 55 but i only found a 52 version for a raspbian system...

And what about autoreg file ? what is this and how find it ?

**Comment by Shellkan** [comment]
Finally i found the problem, my bad.
the copper@vs.inf.ethz.ch  file wasn't at the good place. I have installed it at `~/.mozilla/firefox/xxxxxxxx.default/` instead of `~/.mozilla/firefox/xxxxxxxx.default/extensions/`.
Then have to replace back slash by normal slash for the path to the Copper sources.
Now Copper is available.

**Comment by ameerhazo** [comment]
Hello Shellkan, I'm having the same problem as you are at the moment and I was just wondering what you did after typing the pico command to make the copper@vs.inf.ethz.ch file. I'm redirected into the GNU nano terminal and I was wondering if you changed the file or anything. Thanks for your help.
