### ISSUE TITLE
separate responses to observation requests not matched: "Missing context for Observing.handle()"

### ISSUE THREAD

**Issue by chrysn** [mkovatsc/Copper#7]
when observing a resource whose response takes long enough to generate for the server to send a separate ACK and CON response, copper displays an error message:

    ERROR: UdpClient.onDataAvailable [Missing context for Observing.handle()]
    (Make sure to use the correct CoAP version.)

the conversation looks correct in wireshark, and when the server is instructed to piggyback the response, things work fine.

the debug log reads:

```
INFO: Subscribing to /sensorlog
INFO: Registering token 0x96F8
INFO: Storing transaction 65521
=sending CoAP message===
 Type: Confirmable
 Code: GET
 Message ID: 65521
 Options:
  Uri-Host: $MY_HOSTNAME [...]
  Observe: 0 [0]
  Uri-Path: sensorlog [9]
  Token: 0x96F8 [2]
  Block2: 0/0/1024 [1]
 =======================
-sent UDP datagram------
 Length: 57
 -----------------------
-receiving UDP datagram-
 Length: 4
 -----------------------
=received CoAP message==
 Type: Acknowledgment
 Code: EMPTY
 Message ID: 65521
 =======================
INFO: Closing message 65521
INFO: Deregistering token 0x96F8
INFO: defaultHandler()
-receiving UDP datagram-
 Length: 111
 -----------------------
=received CoAP message==
 Type: Confirmable
 Code: 2.05 Content
 Message ID: 10835
 Options:
  Observe: 2183 [2]
  Token: 0x96F8 [2]
  Block2: 0/0/1024 [1]
 Payload: 98 bytes
{"bt":1424024042.423,"e":[{"n":"/s/5/signal","v":-10.9,"t":0},{"n":"/s/5/temp","v":22.275,"t":0}]}
 =======================
INFO: Incoming separate reponse (Token: 0x96F8)
=sending CoAP message===
 Type: Acknowledgment
 Code: EMPTY
 Message ID: 10835
 =======================
-sent UDP datagram------
 Length: 4
 -----------------------
```

**Comment by chrysn** [comment]
it looks like separate response matching does not work for resource discovery either, as similar behavior is shown there. (the immediate response to the Discover button is "ERROR: Main.discoverHandle [Content-Type is null, not 'application/link-format']"; when the actual response arrives, the same error is shown again, but the resource tree is displayed as well.)

**Comment by mkovatsc** [comment]
The issue was something else, but it is fixed now.
